version: '3'
services:
  gateway:
    build:
      context: ./WebDiary_Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  user-service:
    build:
      context: ./WebDiary_UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - backend

  diary-service:
    build:
      context: ./WebDiary_DiaryService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - backend

  planner-service:
    build:
      context: ./WebDiary_PlannerService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diaries
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:
    driver: local

networks:
  backend:
    driver: bridge
